AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String

  StackName:
    Type: String

Conditions:
  IsDevEnvironment: !Equals [!Ref Environment, "dev"]

Resources:
  SecurityGroupGrafanaProm:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to Prometheus and Grafana.
      Tags:
        - Key: Name
          Value: !Join ['-', ['SecurityGroupGrafanaProm', !Ref Environment]]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5601
          ToPort: 5601
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9200
          CidrIp: 0.0.0.0/0

  ElasticIpELK:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EC2InstancePrometheusGrafana:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If
        - IsDevEnvironment
        - ami-0a695f0d95cefc163  # AMI ID for 'dev' environment
        - ami-007855ac798b5175e  # AMI ID for 'prod' environment
      InstanceType: t2.large
      KeyName: turnthepage
      SecurityGroupIds:
        - !Ref SecurityGroupGrafanaProm
      Tags:
        - Key: Name
          Value: !Join ['-', ['PrometheusAndGrafana-bluegreen-', !Ref Environment]]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install wget
          sudo yum install wget -y
          # Download prom_install and grafana_install
          wget https://raw.githubusercontent.com/si3mshady/gh_devsec_ops/main/prom_install.sh
          wget https://raw.githubusercontent.com/si3mshady/gh_devsec_ops/main/grafana_install.sh

          # Make prom_install and grafana_install executable
          chmod +x prom_install.sh
          chmod +x grafana_install.sh

          # Run prom_install
          ./prom_install.sh
          # Run grafana_install
          ./grafana_install.sh

          # Configure Prometheus to forward logs to ELK
          echo "elk_host:${ElasticIpELK.PublicIp}" >> /etc/prometheus/prometheus.yml

#new 
  EC2InstanceELK:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If
        - IsDevEnvironment
        - ami-0a695f0d95cefc163  # AMI ID for 'dev' environment
        - ami-053b0d53c279acc90 # AMI ID for 'prod' environment
      InstanceType: m4.large
      KeyName: turnthepage
      SecurityGroupIds:
        - !Ref SecurityGroupGrafanaProm
      Tags:
        - Key: Name
          Value: !Join ['-', ['ELK-', !Ref Environment]]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Download Elasticsearch
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.1-linux-x86_64.tar.gz

          # Download Logstash
          wget https://artifacts.elastic.co/downloads/logstash/logstash-8.7.1-linux-x86_64.tar.gz

          # Download Kibana
          wget https://artifacts.elastic.co/downloads/kibana/kibana-8.7.1-linux-x86_64.tar.gz

          # Untar the files
          tar -xzf elasticsearch-8.7.1-linux-x86_64.tar.gz
          tar -xzf logstash-8.7.1-linux-x86_64.tar.gz
          tar -xzf kibana-8.7.1-linux-x86_64.tar.gz

          # Move the files to their respective directories
          sudo mv elasticsearch-8.7.1 /opt/elasticsearch
          sudo mv logstash-8.7.1 /opt/logstash
          sudo mv kibana-8.7.1 /opt/kibana

          # Create a symbolic link for Elasticsearch
          sudo ln -s /opt/elasticsearch /usr/local/bin/elasticsearch

          # Create a symbolic link for Logstash
          sudo ln -s /opt/logstash /usr/local/bin/logstash

          # Create a symbolic link for Kibana
          sudo ln -s /opt/kibana /usr/local/bin/kibana

          # # Start Elasticsearch
          # sudo service elasticsearch start

          # # Start Logstash
          # sudo service logstash start

          # # Start Kibana
          # sudo service kibana start

                  

       



Outputs:
  PublicDnsName:
    Value: !GetAtt ElasticIpELK.PublicIp

     
# Save the script to a file (e.g., install_elk.sh), make it executable using the command chmod +x install_elk.sh, and then execute it with ./install_elk.sh.

# This script performs the following steps:

# Updates the system packages.
# Installs the Java Runtime Environment (JRE).
# Downloads and installs Elasticsearch.
# Enables and starts the Elasticsearch service.
# Installs Logstash.
# Enables and starts the Logstash service.
# Installs Kibana.
# Enables and starts the Kibana service.
# After running this script, the ELK stack should be installed and running on your Ubuntu system. You can access Kibana by visiting http://localhost:5601 in your web browser.