version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elk
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx1g
    ports:
      - '9600:9600'
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      - elasticsearch
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk_network

networks:
  elk_network:
    driver: bridge
