version: "3.7"

services:
  filebeat:

    depends_on:
      - elasticsearch
    image: docker.elastic.co/beats/filebeat:7.17.10
    command: filebeat -e -c /usr/share/filebeat/filebeat.yml #reads configuration file
    # command: "setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=['elasticsearch:9200']"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./noSpoon.log:/usr/share/filebeat/noSpoon.log
    restart: always
    networks:
      - elk_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m  # Modified heap size to -Xms256g
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    depends_on:
      - elasticsearch
    container_name: logstash
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - 9600:9600
      - 5044:5044
    # command: logstash -f /usr/share/logstash/pipeline/logstash.conf #redundant was testing 
    # volumes:
      # - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf #configure 
    networks:
      - elk_network
  
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    depends_on:
      - elasticsearch
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk_network

volumes:
  es_data:

networks:
  elk_network:
    driver: bridge


