version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    depends_on:
      - elasticsearch
    container_name: logstash
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx1g
      - LS_OPTS=--path.settings=/usr/share/logstash/config
    ports:
      - 9600:9600
    command: logstash -f /logstash_dir/logstash.conf
    volumes:
      - ./logstash.conf:/logstash_dir/logstash.conf
      - ./logs.log:/logstash_dir/logs.log
    networks:
      - elk_network


  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      - elasticsearch
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk_network

volumes:
  es_data:

networks:
  elk_network:
    driver: bridge