AWSTemplateFormatVersion: '2010-09-09'

# Parameters:
#   YourIP:
#     Type: String
#     Description: IP address allowed for SSH access
#     default: 10.10

Resources:
  # Create an S3 bucket named sreuniversity
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sreuniversity

  # Create an EC2 instance
  SREUNIVERSITY:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c36b3f873d6311d1
      KeyName: turnthepage
      InstanceType: t2.medium
      Tags:
        - Key: Name
          Value: SRE_UNIVERSITY
      SecurityGroups:
        - Ref: SREUNIVERSITYsg
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker git
          echo "Port 3000 opened to public"
         
          sudo docker run -d -p 3000:3000 si3mshady/awsthree:4

  # Create a security group for the EC2 instance
  SREUNIVERSITYsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SREUNIVERSITYsg
      GroupDescription: Security group for SRE_UNIVERSITY instance
      Tags:
        - Key: Name
          Value: turnthepagesg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
