name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Build CloudFormation template
        run: aws cloudformation package --template-file template.yml --output-template-file output.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Test CloudFormation template
        run: aws cloudformation validate-template --template-file output.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy CloudFormation template
        run: aws cloudformation deploy --template-file output.yml --stack-name sre-university --s3-bucket sreuniversity

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli codeguru-reviewer
      - name: Run security scan
        run: codeguru-reviewer scan --source-bucket sreuniversity --source-prefix template.yml

  deploy-if-secure:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy CloudFormation template if secure
        run: |
          findings=$(codeguru-reviewer get-findings --source-bucket sreuniversity --source-prefix template.yml | jq -r '.findings | length')
          if [[ $findings -eq 0 ]]; then
            aws cloudformation deploy --template-file output.yml --stack-name sre-university --s3-bucket sreuniversity
          fi
