AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c36b3f873d6311d1
      InstanceType: t2.large
      KeyName: turnthepage
      SecurityGroupIds:
        - !Ref SecurityGroupGrafanaProm
      Tags:
        - Key: Name
          Value: Prometheus and Grafana
    UserData:
      Fn::Base64: |
        #!/bin/bash

        # Install wget
        sudo yum install wget -y

        # Download prom_install and grafana_install
        wget https://raw.githubusercontent.com/si3mshady/gh_devsec_ops/main/prom_install.sh
        wget https://raw.githubusercontent.com/si3mshady/gh_devsec_ops/main/grafana_install.sh

        # Make prom_install and grafana_install executable
        chmod +x prom_install.sh
        chmod +x grafana_install.sh

        # Run prom_install
        ./prom_install.sh

        # Run grafana_install
        ./grafana_install.sh

  SecurityGroupGrafanaProm:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to Prometheus and Grafana
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
