name: DevSecOps Pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # sudo apt-get update -y
          # sudo apt-get install -y awscli
           echo "Update complete"
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "Build complete"

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # sudo apt-get update
          # sudo apt-get install -y awscli
          echo "Test complete"

      - name: Test CloudFormation template
        run: |
          if grep -q "turnthepage" template.yml; then
            echo "Template contains the string 'turnthepage'"
          else
            echo "Template does not contain the string 'turnthepage'"
          fi

  security-scan:
    runs-on: ubuntu-20.04
    needs: ["test","build"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli
          # echo "Test complete"
      - name: Run security scan
        run: |
          if grep -q "your_regex_pattern" template_grafana.yml; then
            echo "Regex pattern found in template_grafana.yml. Proceeding with deployment."
            exit 1
          else
            echo "Regex pattern not found in template_grafana.yml. Stopping deployment."
          fi

  deploy:
    runs-on: ubuntu-20.04
    needs: ["security-scan","test","build"]
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli
          # echo "Update complete"
      - name: Set AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION=us-east-1
          aws cloudformation deploy --template-file template_grafana.yml --stack-name sreuniversitygrafana2
     