name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Build Cloudformation template
        run: |
          aws cloudformation package --template-file template.yml --output-template-file packaged.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Test Cloudformation template
        run: |
          aws cloudformation validate-template --template-file packaged.yml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "AWS_DEFAULT_REGION=us-east-1" >> ~/.aws/credentials
      - name: Deploy Cloudformation template
        run: |
          aws cloudformation deploy --template-file packaged.yml --stack-name sre-university --s3-bucket sreuniversity

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo apt-get install -y trivy
      - name: Run security scan
        run: |
          trivy image --format=json --severity=CRITICAL,HIGH,MEDIUM localhost:5000/sreuniversity/template.yml

  deploy-if-secure:
    runs-on: ubuntu-latest
    needs:
      - security-scan
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy Cloudformation template if secure
        run: |
          if [[ $(trivy image --format=json --severity=CRITICAL,HIGH,MEDIUM localhost:5000/sreuniversity/template.yml | jq -r '.vulnerabilities | length') -eq 0 ]]; then
            aws cloudformation deploy --template-file packaged.yml --stack-name sre-university --s3-bucket sreuniversity
          fi
