name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "Build complete"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Test CloudFormation template
        run: |
          if grep -q "turnthepage" template.yml; then
            echo "Template contains the string 'turnthepage'"
          else
            echo "Template does not contain the string 'turnthepage'"
          fi

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Run security scan
        run: |
          if grep -q "your_regex_pattern" template.yml; then
            echo "Regex pattern found in template.yml. Proceeding with deployment."
            exit 1
          else
            echo "Regex pattern not found in template.yml. Stopping deployment."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, security-scan]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tekloon-test-stack
          template: template.yml
          no-fail-on-empty-changeset: "1"
          # parameter-overrides: "EC2InstanceType=t2.micro"
