name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "Build complete"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Test CloudFormation template
        run: |
          if grep -q "turnthepage" template.yml; then
            echo "Template contains the string 'turnthepage'"
          else
            echo "Template does not contain the string 'turnthepage'"
          fi

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Run security scan
        run: |
          if grep -q "your_regex_pattern" template.yml; then
            echo "Regex pattern found in template.yml. Proceeding with deployment."
            exit 1
          else
            echo "Regex pattern not found in template.yml. Stopping deployment."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and Set up AWS credentials
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::201565661725:role/CloudF
          role-session-name: MySessionName
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "AWS_DEFAULT_REGION=us-east-1" >> ~/.aws/credentials
          aws cloudformation deploy --template-file template.yml --stack-name sre-university 
